### ISSUE TITLE
【建议】为用户身份起别名，以方便切换

### ISSUE THREAD

**Issue by iron2column** [alqmc/gacm#3]
能否添加新的命令如`alias`以达到为不同用户起不同的名字，从而进行切换：
`gacm alias xxx`
`gacm use xxx`

**Comment by alqmc** [comment]
是指用户名相同，但邮箱不一致的情况吗

**Comment by iron2column** [comment]
也可以处理这种情况，不过我的想法是：由于我的两个用户名`name`一个为中文字符，另一个又为长字符串，所以在切换时相对麻烦，所以希望能通过起别名的方式，如`u1`、`u2`这样进行切换时能方便些 :D
